production:
  server: "https://private-pub-heroku.herokuapp.com/faye"

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension.

  secret_token: "8ecad6bdc250561f3c4974c46ff3a46df3faf4b4635088e445dfc97968b01d31"
  signature_expiration: 3600 # one day
